name: mobility_features
description: Calculation of real-time mobility features like places, stops, and home stay
version: 3.1.0
homepage: https://github.com/cph-cachet/flutter-plugins/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_cluster: ^0.3.0
  stats: ^2.0.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: